// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from proj.djinni

package com.ezored.sample;

/** Platform-Specific implementation of HelloWorldProxy Class */
public abstract class HelloWorldProxy {
    public abstract void showGreetingMessageAlert();
}
